# Generated by Django 5.1.7 on 2025-03-24 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_caja', models.AutoField(primary_key=True, serialize=False)),
                ('abierta_caja', models.IntegerField(default=0)),
                ('fecha_hs_aper_caja', models.DateTimeField(auto_now_add=True)),
                ('fecha_hs_cier_caja', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial_caja', models.FloatField()),
                ('total_ingresos_caja', models.FloatField(blank=True, null=True)),
                ('total_egresos_caja', models.FloatField(blank=True, null=True)),
                ('saldo_caja', models.FloatField(blank=True, null=True)),
                ('id_empl', models.ForeignKey(db_column='id_empl', on_delete=django.db.models.deletion.DO_NOTHING, to='empleados.empleados')),
            ],
        ),
    ]
