# Generated by Django 5.1.7 on 2025-03-23 15:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_empl', models.BigIntegerField(help_text='Ingrese el número de DNI del empleado.', unique=True, validators=[django.core.validators.MinValueValidator(1000000, message='El DNI debe tener al menos 7 dígitos.'), django.core.validators.MaxValueValidator(99999999, message='El DNI no puede tener más de 8 dígitos.')], verbose_name='DNI')),
                ('nombre_empl', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido_empl', models.CharField(max_length=50, verbose_name='Apellido')),
                ('domicilio_empl', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('telefono_empl', models.BigIntegerField(blank=True, help_text='Ingrese el número de teléfono del empleado.', null=True, validators=[django.core.validators.MinValueValidator(100000000, message='El teléfono debe tener al menos 9 dígitos.'), django.core.validators.MaxValueValidator(999999999999, message='El teléfono no puede tener más de 12 dígitos.')], verbose_name='Teléfono')),
                ('correo_empl', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('rango_emp', models.CharField(choices=[('COC', 'Cocinero'), ('MOZ', 'Mozo'), ('CAJ', 'Cajero')], default='MOZ', max_length=3, verbose_name='Rango')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
