# Generated by Django 5.1.7 on 2025-03-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empl', models.AutoField(primary_key=True, serialize=False)),
                ('dni_empl', models.IntegerField(unique=True)),
                ('nombre_empl', models.CharField(max_length=50)),
                ('apellido_empl', models.CharField(max_length=50)),
                ('domicilio_empl', models.CharField(max_length=50)),
                ('telefono_empl', models.IntegerField(blank=True, null=True)),
                ('correo_empl', models.EmailField(blank=True, max_length=50, null=True)),
                ('rango_emp', models.CharField(choices=[('COC', 'Cocinero'), ('MOZ', 'Mozo'), ('CAJ', 'Cajero')], default='MOZ', max_length=3)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
