# Generated by Django 5.1.7 on 2025-03-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleados_apellido_empl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='apellido_empl',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='correo_empl',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='dni_empl',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='domicilio_empl',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='id_empl',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre_empl',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='rango_emp',
            field=models.CharField(choices=[('COC', 'Cocinero'), ('MOZ', 'Mozo'), ('CAJ', 'Cajero')], default='MOZ', max_length=3),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono_empl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
