# Generated by Django 5.1.7 on 2025-03-23 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleados_apellido_empl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='apellido_empl',
            field=models.CharField(help_text='Ingrese el apellido del empleado.', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='correo_empl',
            field=models.EmailField(blank=True, help_text='Ingrese el correo electrónico del empleado.', max_length=100, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='dni_empl',
            field=models.BigIntegerField(help_text='Ingrese el número de DNI del empleado.', unique=True, validators=[django.core.validators.MinValueValidator(1000000, message='El DNI debe tener al menos 7 dígitos.'), django.core.validators.MaxValueValidator(99999999, message='El DNI no puede tener más de 8 dígitos.')], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='domicilio_empl',
            field=models.CharField(help_text='Ingrese la dirección del empleado.', max_length=50, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='id_empl',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Empleado'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre_empl',
            field=models.CharField(help_text='Ingrese el nombre del empleado.', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='rango_emp',
            field=models.CharField(choices=[('COC', 'Cocinero'), ('MOZ', 'Mozo'), ('CAJ', 'Cajero')], default='MOZ', help_text='Seleccione el rango del empleado.', max_length=3, verbose_name='Rango'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono_empl',
            field=models.BigIntegerField(blank=True, help_text='Ingrese el número de teléfono del empleado.', null=True, validators=[django.core.validators.MinValueValidator(100000000, message='El teléfono debe tener al menos 9 dígitos.'), django.core.validators.MaxValueValidator(999999999999, message='El teléfono no puede tener más de 12 dígitos.')], verbose_name='Teléfono'),
        ),
    ]
