# Generated by Django 5.1.7 on 2025-03-24 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prod', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio_prod', models.FloatField(verbose_name='Precio')),
                ('stock_min_prod', models.IntegerField()),
                ('stock_actual_prod', models.IntegerField(verbose_name='Stock actual')),
                ('punto_reposicion_prod', models.IntegerField()),
                ('stock_max_prod', models.IntegerField()),
                ('existencia_insumo', models.IntegerField()),
                ('insumo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProvProductos',
            fields=[
                ('idprov_productos', models.IntegerField(primary_key=True, serialize=False)),
                ('id_prod', models.IntegerField()),
                ('descripcion_prod_prov', models.TextField()),
                ('id_prov', models.ForeignKey(db_column='id_prov', on_delete=django.db.models.deletion.DO_NOTHING, to='proveedores.proveedor')),
            ],
        ),
    ]
